### ISSUE TITLE
Add Permission Rule to test

### ISSUE THREAD

**Issue by AndreSand** [AdamMc331/EspressoPatronum#1]
Hi Adam,
Very good tutorial 👍 
When I run RegistrationTests on my Pixel device (Running Android 8.1) I get error:
`java.lang.RuntimeException: Unable to create output dir: /storage/emulated/0/app_spoon-screenshots`

![screen shot 2018-05-01 at 3 28 36 pm](https://user-images.githubusercontent.com/8283868/39496705-7d34f2b6-4d54-11e8-8b31-d106c7c93ee3.png)

I fixed by adding Permission Rule to RegistrationTests
```@JvmField
    @Rule
    var mPermissionsRule = GrantPermissionRule.grant(WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE)
```

I can open PR if you want, thanks :)

**Comment by AdamMc331** [comment]
Hey Andre! Did you try running this via the run button, as opposed to the spoon gradle plugin? That seems to be what would cause this.

Just acknowledging receipt of this, but I may not be able to get to it until tomorrow. If you want to make a PR, I can test your branch and merge if it works. :) Thanks!

**Comment by AndreSand** [comment]
Yes I ran the tests from the run button.

Ok cool, let me open a PR.
Thanks :)

**Comment by AdamMc331** [comment]
Thanks!
